### ISSUE TITLE
OpenVR Plugin works in Editor; Defaults to SteamVR background + no tracking on Build.

### ISSUE THREAD

**Issue by charlicopter** [ValveSoftware/unity-xr-plugin#10]
Editor play with Vive HMD + wands, and Index Controllers work fine (except for trackers, which are not detected).
But playing a **build** with OpenVR Plugin only detects the Lighthouse base stations. HMD defaults to SteamVR background environment. 

Unity 2020.1.0b12

**Comment by 1runeberg** [comment]
Hi - @charlicopter @yaddatrance @IronWarrior - Sorry for the delay, can you confirm if you're using SteamVR Beta? We have had issues with builds if you're not using Beta. Another Preview should be up soon that should resolve this.

**Comment by yaddatrance** [comment]
I'm using the version linked here... https://github.com/ValveSoftware/unity-xr-plugin/releases/tag/installer (which was itself referred from https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.6.0b2)

**Comment by IronWarrior** [comment]
I wasn't using the beta before, but upgrading to it didn't resolve the issue. It sounds like yall have a handle on it, but if not [here's a build](https://drive.google.com/file/d/1mfRQzpPIaVTQTG2hZjohTOcVG6XWWrng/view?usp=sharing) I made off [this project](https://drive.google.com/file/d/13Ay4T49ErG6QySW4ezgXUrh1-PC1bpoL/view?usp=sharing).

**Comment by zite** [comment]
Thanks for the update
