### ISSUE TITLE
DepthNormals texture created without depth buffer

### ISSUE THREAD

**Issue by CarpetHead** [ValveSoftware/unity-xr-plugin#58]
Currently while using this plugin alongside traditional image effects, the _CameraDepthNormals texture is completely broken. It looks as though this is because the RenderTexture is created without a depth buffer. 

Video here https://streamable.com/xmjmv4

**Comment by 1runeberg** [comment]
Hi @CarpetHead - we're adding depth buffers in the next release. we'd like to test your issue specifically against it though - do you have a minimal repro for us?

**Comment by CarpetHead** [comment]
[ShaderRepro.zip](https://github.com/ValveSoftware/unity-xr-plugin/files/5597109/ShaderRepro.zip)

DepthNormalsIssue Scene:
Here is a repo of two different issues. Toggle in and out of play mode to see the issue with the depthnormals of the cubes.

As a workaround, I tried to render the DepthNormalsTexture with a seperate camera, but you can see in the TargetTextureIssue scene, even doing this has an issue. A final blit on the extra camera causes a grey screen rather than the desired depth normals texture. Toggle in and out of play mode to see the issue.

**Comment by CarpetHead** [comment]
I had a go at compiling the UpdatedHeaders branch locally and putting in my Packages folder, and this issue doesn't seem to be resolved. Is it fixed in the repro case for you?

**Comment by zite** [comment]
Hi, thanks for reporting the issue. This should be fixed in the latest release. You're welcome to give it a try and let us know if it solves the problem.
https://github.com/ValveSoftware/unity-xr-plugin/releases/tag/v1.1.1b

**Comment by CarpetHead** [comment]
Hmm, I'm not sure exactly what the root cause of the issue is, but I can still reproduce it in the above beta release:
XR Enabled
![image](https://user-images.githubusercontent.com/7747065/102081421-1bae4b80-3e08-11eb-8897-cf990c8c0309.png)
XR Disabled
![image](https://user-images.githubusercontent.com/7747065/102081426-1fda6900-3e08-11eb-99e6-f380a3ba1c21.png)

you can see the depth sorting of the depthnormals texture is wrong while the xr plugin is active

**Comment by 1runeberg** [comment]
Hi @CarpetHead - The depth textures have been added in the latest beta, the main camera preview and VR results appear correct to me based on the scene layout:

![image](https://user-images.githubusercontent.com/17371351/102281011-43c1ba00-3f82-11eb-9358-639b555482f3.png)

Perhaps I'm misunderstanding your issue?
