### ISSUE TITLE
Log spam with Single Pass Instanced mode and Tracked Pose Driver

### ISSUE THREAD

**Issue by Clavus** [ValveSoftware/unity-xr-plugin#6]
This error is spammed in the log when using the Single Pass Instanced rendering mode:
![image](https://user-images.githubusercontent.com/670995/86739130-f0902680-c035-11ea-8ee4-f10bef440678.png)

Here's the rig I set up, with just a tracked pose driver for the head:
![image](https://user-images.githubusercontent.com/670995/86739205-000f6f80-c036-11ea-84d4-b19a2c2e8032.png)

Unity 2019.4.2f1, SteamVR 1.13.9, using an Oculus Quest over Link.

This does not occur with Multi Pass rendering. It also does not occur when using Single Pass Instanced rendering via the Oculus XR plugin, for comparison.

**Comment by 1runeberg** [comment]
Hi @Clavus - Can you confirm please if you are still getting this with the latest preview update?

**Comment by Transzendental** [comment]
Is there any progress on this?

Im getting the same error on Unity 2020.1 and SteamVR 2.6.1

**Comment by HermesBoots** [comment]
I also have this issue in Unity 2019.4, and it makes the entire game and scene views pink. Multi-pass works fine.

**Comment by zite** [comment]
This should be fixed in the latest release. You're welcome to give it a try and let us know if it solves the problem.
https://github.com/ValveSoftware/unity-xr-plugin/releases/tag/v1.1.1b

**Comment by kisak-valve** [comment]
Closing per the last comment.

**Comment by Transzendental** [comment]
I still have this issue, with Unity 2021.1, SteamVR 2.7.3 and an HTC Vive.

**Comment by nikolicd** [comment]
This is still an issue

**Comment by zite** [comment]
> This is still an issue

You get this exact log spam with single pass instanced rendering?
